---
deployment:
  tasks:
    - export DEPLOYPATH=/home/moziaida/public_html/
    - ng build --configuration=production --output-path=dist/moziaarti-web-app
    - /bin/cp -R dist/moziaarti-web-app/* $DEPLOYPATH